#!/bin/sh
#
# chkconfig: 234 90 10
# description: Metrilyx script to manage all metrilyx processes.
#

[ -f "/etc/rc.d/init.d/functions" ] && . /etc/rc.d/init.d/functions

NAME="metrilyx"
SERVICE_START_ORDER="metrilyx-dataserver metrilyx-modelmanager celeryd celerybeat"
SERVICE_STOP_ORDER="metrilyx-dataserver metrilyx-modelmanager celerybeat celeryd"
start() {
	for service in ${SERVICE_START_ORDER}; do
		service $service start
	done
}
status() {
	for service in ${SERVICE_START_ORDER}; do
		service $service status
	done
}
stop() {
	for service in ${SERVICE_STOP_ORDER}; do
		service $service stop
	done
}

case "$1" in
	start)
		start;
		;;
	stop)
		stop;
		;;
	status)
		status;
		;;
	*)
		echo "$0 [start|stop|status]"
		exit 1;
esac
exit 0
