#!/bin/sh
#
# chkconfig: 234 90 10
# description: Metilyx API server.
#

[ -f "/etc/rc.d/init.d/functions" ] && . /etc/rc.d/init.d/functions

NAME="metrilyx-modelmanager"
BIN=uwsgi
APP_HOME="/opt/metrilyx"
LOGFILE=/var/log/metrilyx/${NAME}.log
PGREP="/usr/bin/pgrep -f"

DEFAULT_OPTS="--ini ${APP_HOME}/etc/metrilyx/uwsgi.conf"

RETVAL=0

start() {
	PIDS=`${PGREP} "${BIN} ${DEFAULT_OPTS}" | xargs`;
	if [ "$PIDS" = "" ]; then
		echo -n "${NAME} starting... "
		${BIN} ${DEFAULT_OPTS} > ${LOGFILE} 2>&1 &
		sleep 1;
		PIDS=`${PGREP} "${BIN} ${DEFAULT_OPTS}" | xargs`;
		if [ "$PIDS" = "" ]; then
			echo "[failed]";
			RETVAL=2;
		else
			echo "[ok]";
		fi
	else
		echo -n "${NAME} running... ${PIDS}";
		RETVAL=1;
	fi
}
status() {
	PIDS=`${PGREP} "${BIN} ${DEFAULT_OPTS}" | xargs`;
	if [ "$PIDS" = "" ]; then
		echo "${NAME} not running";
	else
		echo "${NAME} running... $PIDS";
	fi
}
stop() {
	echo -n "Stopping... "
	${PGREP} "${BIN} ${DEFAULT_OPTS}" > /tmp/metrilyx-modelmanager.pid;
	${BIN} --stop /tmp/metrilyx-modelmanager.pid;
	rm -rf /tmp/metrilyx-modelmanager.pid;
	echo "[ok]";
}
reload() {
	echo -n "Reloading... ";
	${PGREP} "${BIN} ${DEFAULT_OPTS}" > /tmp/metrilyx-modelmanager.pid;
	${BIN} --reload /tmp/metrilyx-modelmanager.pid
	rm -rf /tmp/metrilyx-modelmanager.pid;
	echo "[ok]";
}

case "$1" in
	start)
		start;
		;;
	stop)
		stop;
		;;
	status)
		status;
		;;
	reload)
		reload;
		;;
	restart)
		$0 stop
		sleep 3
		$0 start
		;;
esac
exit $RETVAL
