#!/bin/sh
#
# chkconfig: 234 90 10
# description: Metilyx API server.
#

[ -f "/etc/rc.d/init.d/functions" ] && . /etc/rc.d/init.d/functions

if [ -f "/etc/sysconfig/metrilyx" ]; then
	. /etc/sysconfig/metrilyx
else
	echo "/etc/sysconfig/metrilyx not found!";
	exit 1;
fi

NAME="metrilyx-modelmanager"
BIN="/opt/metrilyx/usr/bin/uwsgi"
APP_HOME="/opt/metrilyx"
LOGFILE="${APP_HOME}/log/${NAME}.log"
PIDFILE="/tmp/${NAME}.pid"

PGREP="/usr/bin/pgrep -f"

DEFAULT_OPTS="--ini ${APP_HOME}/etc/metrilyx/uwsgi.conf"

RETVAL=0

PYTHON_EGG_CACHE="/dev/shm/metrilyx"

start() {
	PIDS=`${PGREP} "${BIN} ${DEFAULT_OPTS}" | xargs`;
	if [ "$PIDS" = "" ]; then
		echo -n "${NAME} starting... "
		PYTHONPATH=${PYTHONPATH} PYTHON_EGG_CACHE=$PYTHON_EGG_CACHE METRILYX_HOME=${APP_HOME} ${BIN} ${DEFAULT_OPTS} > ${LOGFILE} 2>&1 &
		sleep 1;
		PIDS=`${PGREP} "${BIN} ${DEFAULT_OPTS}" | xargs`;
		if [ "$PIDS" = "" ]; then
			echo "[failed]";
			RETVAL=2;
		else
			echo "[ok]";
		fi
	else
		echo -n "${NAME} running... ${PIDS}";
		RETVAL=1;
	fi
}
status() {
	PIDS=`${PGREP} "${BIN} ${DEFAULT_OPTS}" | xargs`;
	if [ "$PIDS" = "" ]; then
		echo "${NAME} not running";
	else
		echo "${NAME} running... $PIDS";
	fi
}
stop() {
	echo -n "${NAME} stopping... "
	${PGREP} "${BIN} ${DEFAULT_OPTS}" > $PIDFILE;
	${BIN} --stop $PIDFILE;
	rm -rf $PIDFILE;
	echo "[ok]";
}
reload() {
	echo -n "Reloading... ";
	${PGREP} "${BIN} ${DEFAULT_OPTS}" > $PIDFILE;
	${BIN} --reload $PIDFILE
	rm -rf $PIDFILE;
	echo "[ok]";
}

case "$1" in
	start)
		start;
		;;
	stop)
		stop;
		;;
	status)
		status;
		;;
	reload)
		reload;
		;;
	restart)
		$0 stop
		sleep 3
		$0 start
		;;
esac
exit $RETVAL
